package Views.ServiceManagement;
import Model.Services;
import Controllers.ServiceControllers;
import javax.swing.JOptionPane;

public class EditServiceView extends javax.swing.JDialog {
    private static final ServiceControllers control = new ServiceControllers();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditServiceView.class.getName());

    /**
     * Creates new form EditCustomerView
     * @param service
     */
    
    public void loadServiceData(Services service) {
        ServiceIDField.setText(String.valueOf(service.getServiceID()));
        ServiceNameField.setText(service.getServiceName());
        ServicePriceField.setText(String.valueOf(service.getPrice()));
        ServiceDurationField.setText(String.valueOf(service.getDurationMinutes()));
        ServiceStatusField.setSelectedItem(service.getStatus());
    }
    
    public EditServiceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ServiceIDField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CancelUpdateButton = new javax.swing.JButton();
        UpdateServiceButton = new javax.swing.JButton();
        ServiceStatusField = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ServiceDurationField = new javax.swing.JTextField();
        ServiceNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ServicePriceField = new javax.swing.JTextField();

        ServiceIDField.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(190, 52, 85));

        jPanel2.setBackground(new java.awt.Color(255, 224, 227));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 32, 56));
        jLabel1.setText("Edit Service");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        CancelUpdateButton.setBackground(new java.awt.Color(140, 38, 62));
        CancelUpdateButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        CancelUpdateButton.setForeground(new java.awt.Color(255, 224, 227));
        CancelUpdateButton.setText("Cancel");
        CancelUpdateButton.addActionListener(this::CancelUpdateButtonActionPerformed);

        UpdateServiceButton.setBackground(new java.awt.Color(255, 224, 227));
        UpdateServiceButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        UpdateServiceButton.setForeground(new java.awt.Color(190, 52, 85));
        UpdateServiceButton.setText("Update");
        UpdateServiceButton.addActionListener(this::UpdateServiceButtonActionPerformed);

        ServiceStatusField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ServiceStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Maintenance" }));
        ServiceStatusField.addActionListener(this::ServiceStatusFieldActionPerformed);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 224, 227));
        jLabel6.setText("Status: *");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 224, 227));
        jLabel5.setText("Service Duration (in mins.): *");

        ServiceDurationField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ServiceDurationField.setForeground(new java.awt.Color(47, 32, 56));
        ServiceDurationField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ServiceDurationField.setSelectionColor(new java.awt.Color(241, 206, 215));
        ServiceDurationField.addActionListener(this::ServiceDurationFieldActionPerformed);

        ServiceNameField.setBackground(new java.awt.Color(255, 239, 241));
        ServiceNameField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ServiceNameField.setForeground(new java.awt.Color(47, 32, 56));
        ServiceNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ServiceNameField.setDisabledTextColor(new java.awt.Color(255, 224, 227));
        ServiceNameField.setSelectionColor(new java.awt.Color(241, 206, 215));
        ServiceNameField.addActionListener(this::ServiceNameFieldActionPerformed);

        jLabel3.setBackground(new java.awt.Color(255, 224, 227));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 224, 227));
        jLabel3.setText("Service Name: *");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 224, 227));
        jLabel7.setText("Service Price: *");

        ServicePriceField.setBackground(new java.awt.Color(255, 239, 241));
        ServicePriceField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ServicePriceField.setForeground(new java.awt.Color(47, 32, 56));
        ServicePriceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ServicePriceField.setDisabledTextColor(new java.awt.Color(255, 224, 227));
        ServicePriceField.setSelectionColor(new java.awt.Color(241, 206, 215));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServiceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ServicePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ServiceStatusField, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(UpdateServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CancelUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ServiceDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServiceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServicePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServiceDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServiceStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ServiceNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceNameFieldActionPerformed

    private void ServiceDurationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceDurationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceDurationFieldActionPerformed

    private void UpdateServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateServiceButtonActionPerformed
        String service_id, service_name, service_duration, service_price, service_status;
        service_id = ServiceIDField.getText().trim();
        service_name = ServiceNameField.getText().trim();
        service_duration = ServiceDurationField.getText();
        service_price = ServicePriceField.getText().trim();
        service_status = (String) ServiceStatusField.getSelectedItem();
        
        String message = control.UpdateServiceDetails(service_id, service_name, service_price, service_duration, service_status);
        JOptionPane.showMessageDialog(null, message);
        ServiceView.getInstance().loadServicesToTable();
        this.dispose(); 
    }//GEN-LAST:event_UpdateServiceButtonActionPerformed

    private void CancelUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelUpdateButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelUpdateButtonActionPerformed

    private void ServiceStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceStatusFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditServiceView dialog = new EditServiceView();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelUpdateButton;
    private javax.swing.JTextField ServiceDurationField;
    private javax.swing.JTextField ServiceIDField;
    private javax.swing.JTextField ServiceNameField;
    private javax.swing.JTextField ServicePriceField;
    private javax.swing.JComboBox<String> ServiceStatusField;
    private javax.swing.JButton UpdateServiceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
