/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.ServiceManagement;
//Import this file
import Views.BaseFrame;
import javax.swing.JOptionPane;

//Change the extends to BaseFrame
public class serviceMenuView extends BaseFrame{
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(serviceMenuView.class.getName());
    
    public serviceMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        AddServicePanel = new javax.swing.JPanel();
        AddServiceTrigger = new javax.swing.JLabel();
        EditServicePanel = new javax.swing.JPanel();
        EditServiceTrigger = new javax.swing.JLabel();
        RemoveServicePanel = new javax.swing.JPanel();
        RemoveServiceTrigger = new javax.swing.JLabel();
        DashboardPanel = new javax.swing.JPanel();
        DashboardTrigger = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        AddServicePanel.setBackground(new java.awt.Color(153, 255, 255));
        AddServicePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddServicePanel.setFocusCycleRoot(true);
        AddServicePanel.setLayout(new java.awt.BorderLayout());

        AddServiceTrigger.setBackground(new java.awt.Color(153, 255, 255));
        AddServiceTrigger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddServiceTrigger.setText("ADD SERVICE");
        AddServiceTrigger.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddServiceTrigger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddServiceTriggerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddServiceTriggerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddServiceTriggerMouseExited(evt);
            }
        });
        AddServicePanel.add(AddServiceTrigger, java.awt.BorderLayout.CENTER);

        jPanel4.add(AddServicePanel);

        EditServicePanel.setBackground(new java.awt.Color(153, 255, 255));
        EditServicePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EditServicePanel.setLayout(new java.awt.BorderLayout());

        EditServiceTrigger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditServiceTrigger.setText("EDIT SERVICE");
        EditServiceTrigger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditServiceTriggerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditServiceTriggerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditServiceTriggerMouseExited(evt);
            }
        });
        EditServicePanel.add(EditServiceTrigger, java.awt.BorderLayout.CENTER);

        jPanel4.add(EditServicePanel);

        RemoveServicePanel.setBackground(new java.awt.Color(153, 255, 255));
        RemoveServicePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RemoveServicePanel.setLayout(new java.awt.BorderLayout());

        RemoveServiceTrigger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RemoveServiceTrigger.setText("REMOVE SERVICE");
        RemoveServiceTrigger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveServiceTriggerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemoveServiceTriggerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemoveServiceTriggerMouseExited(evt);
            }
        });
        RemoveServicePanel.add(RemoveServiceTrigger, java.awt.BorderLayout.CENTER);

        jPanel4.add(RemoveServicePanel);

        DashboardPanel.setBackground(new java.awt.Color(153, 255, 255));
        DashboardPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DashboardPanel.setLayout(new java.awt.BorderLayout());

        DashboardTrigger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DashboardTrigger.setText("DASHBOARD");
        DashboardTrigger.setToolTipText("");
        DashboardTrigger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashboardTrigger.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DashboardTrigger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardTriggerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardTriggerMouseExited(evt);
            }
        });
        DashboardPanel.add(DashboardTrigger, java.awt.BorderLayout.CENTER);

        jPanel4.add(DashboardPanel);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(486, 60));

        jPanel13.setPreferredSize(new java.awt.Dimension(326, 60));

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel14.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Search");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setPreferredSize(new java.awt.Dimension(75, 100));
        jPanel14.add(jButton3);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Reset");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel14.add(jButton4);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel3.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service Name", "Price", "Duration", "Status"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AddServiceTriggerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddServiceTriggerMouseClicked
        // --------------Add this when switching views ----------------
        addServiceView service = new addServiceView();
        service.setExtendedState(this.getExtendedState()); // copy state
        service.setVisible(true);
        this.dispose();
        // ------------------------------------------------------------
    }//GEN-LAST:event_AddServiceTriggerMouseClicked

    private void RemoveServiceTriggerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveServiceTriggerMouseClicked
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you would like to delete this service?");
        
        if(choice == JOptionPane.YES_OPTION){
            System.out.println("Service Deleted");
        }
        else if(choice == JOptionPane.NO_OPTION){
            System.out.println("Deletion Cancelled");
        }
        else if(choice == JOptionPane.CANCEL_OPTION){
            System.out.println("Option Cancelled");
        }
        
        else if(choice == JOptionPane.CLOSED_OPTION){
            System.out.println("Closed Option");
        }
    }//GEN-LAST:event_RemoveServiceTriggerMouseClicked

    private void EditServiceTriggerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditServiceTriggerMouseClicked
        // --------------Add this when switching views ----------------
        editServiceView service = new editServiceView();
        service.setExtendedState(this.getExtendedState()); // copy state
        service.setVisible(true);
        this.dispose();
        // ------------------------------------------------------------
    }//GEN-LAST:event_EditServiceTriggerMouseClicked

    private void AddServiceTriggerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddServiceTriggerMouseEntered
        AddServicePanel.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_AddServiceTriggerMouseEntered

    private void AddServiceTriggerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddServiceTriggerMouseExited
        AddServicePanel.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_AddServiceTriggerMouseExited

    private void EditServiceTriggerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditServiceTriggerMouseEntered
        EditServicePanel.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_EditServiceTriggerMouseEntered

    private void EditServiceTriggerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditServiceTriggerMouseExited
        EditServicePanel.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_EditServiceTriggerMouseExited

    private void RemoveServiceTriggerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveServiceTriggerMouseEntered
        RemoveServicePanel.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_RemoveServiceTriggerMouseEntered

    private void RemoveServiceTriggerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveServiceTriggerMouseExited
        RemoveServicePanel.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_RemoveServiceTriggerMouseExited

    private void DashboardTriggerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardTriggerMouseEntered
        DashboardPanel.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_DashboardTriggerMouseEntered

    private void DashboardTriggerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardTriggerMouseExited
        DashboardPanel.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_DashboardTriggerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new serviceMenuView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddServicePanel;
    private javax.swing.JLabel AddServiceTrigger;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JLabel DashboardTrigger;
    private javax.swing.JPanel EditServicePanel;
    private javax.swing.JLabel EditServiceTrigger;
    private javax.swing.JPanel RemoveServicePanel;
    private javax.swing.JLabel RemoveServiceTrigger;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
