package Views.ServiceManagement;
import Controllers.ServiceControllers;
import javax.swing.JOptionPane;
import Model.Services;

public class AddServiceView extends javax.swing.JDialog {
    private static ServiceControllers control = new ServiceControllers();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddServiceView.class.getName());

    public AddServiceView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setServiceData(String name, String price, String duration, String status) {
    ServiceNameField.setText(name);       // your JTextField for service name
    ServicePriceField.setText(price);     // your JTextField for price
    ServiceDurationField.setText(duration); // your JTextField for duration
    ServiceStatusField.setSelectedItem(status); // your JComboBox for status
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ServicePriceField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ServiceDurationField = new javax.swing.JTextField();
        AddServiceButton = new javax.swing.JButton();
        CancelAddButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ServiceNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ServiceStatusField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 224, 227));

        jPanel2.setBackground(new java.awt.Color(190, 52, 85));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 224, 227));
        jLabel1.setText("Add New Service");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 24, 29));
        jLabel3.setText("Service Name");

        ServicePriceField.setBackground(new java.awt.Color(255, 239, 241));
        ServicePriceField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ServicePriceField.setForeground(new java.awt.Color(48, 24, 29));
        ServicePriceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ServicePriceField.setSelectionColor(new java.awt.Color(210, 90, 119));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 24, 29));
        jLabel4.setText("Service Duration (in mins.): *");

        ServiceDurationField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ServiceDurationField.setForeground(new java.awt.Color(48, 24, 29));
        ServiceDurationField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ServiceDurationField.setSelectionColor(new java.awt.Color(210, 90, 119));

        AddServiceButton.setBackground(new java.awt.Color(190, 52, 85));
        AddServiceButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        AddServiceButton.setForeground(new java.awt.Color(255, 224, 227));
        AddServiceButton.setText("Save");
        AddServiceButton.setFocusPainted(false);
        AddServiceButton.setFocusable(false);
        AddServiceButton.addActionListener(this::AddServiceButtonActionPerformed);

        CancelAddButton.setBackground(new java.awt.Color(255, 239, 241));
        CancelAddButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        CancelAddButton.setForeground(new java.awt.Color(190, 52, 85));
        CancelAddButton.setText("Cancel");
        CancelAddButton.setFocusPainted(false);
        CancelAddButton.setFocusable(false);
        CancelAddButton.addActionListener(this::CancelAddButtonActionPerformed);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(48, 24, 29));
        jLabel7.setText("Service Price: *");

        ServiceNameField.setBackground(new java.awt.Color(255, 239, 241));
        ServiceNameField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ServiceNameField.setForeground(new java.awt.Color(48, 24, 29));
        ServiceNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ServiceNameField.setSelectionColor(new java.awt.Color(210, 90, 119));
        ServiceNameField.addActionListener(this::ServiceNameFieldActionPerformed);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 24, 29));
        jLabel6.setText("Status: *");

        ServiceStatusField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ServiceStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Maintenance" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(154, 154, 154))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ServiceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(131, 131, 131))
                                    .addComponent(ServicePriceField)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ServiceStatusField, javax.swing.GroupLayout.Alignment.LEADING, 0, 460, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ServiceDurationField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServicePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServiceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServiceDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServiceStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAddButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelAddButtonActionPerformed

    private void ServiceNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceNameFieldActionPerformed

    private void AddServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddServiceButtonActionPerformed
        Services service = new Services();
        
        service.setServiceName(ServiceNameField.getText().trim());
        service.setPrice(ServicePriceField.getText().trim());
        service.setDurationMinutes(ServiceDurationField.getText().trim());
        service.setStatus(ServiceStatusField.getSelectedItem().toString().trim());
        
        if(control.AddServiceProcess(service)){
            ServiceView.getInstance().loadServicesToTable();;
            this.dispose();
        }
    }//GEN-LAST:event_AddServiceButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ServiceView dialog = new ServiceView();
        dialog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddServiceView dialog = new AddServiceView();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddServiceButton;
    private javax.swing.JButton CancelAddButton;
    private javax.swing.JTextField ServiceDurationField;
    private javax.swing.JTextField ServiceNameField;
    private javax.swing.JTextField ServicePriceField;
    private javax.swing.JComboBox<String> ServiceStatusField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
